repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    files: "notebooks/*.ipynb"

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black-jupyter
        args: [--line-length=120]
    files: "notebooks/*.ipynb"
