repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        files: notebooks\/.*\.ipynb

# -   repo: https://github.com/psf/black
#     rev: 22.1.0
#     hooks:
#     -   id: black-jupyter
#         args: ["--verbose", "--line-length=120"]
#         files: notebooks\/.*\.ipynb
