repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        files: notebooks/

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black-jupyter
        args: [--line-length=120]
        files: notebooks/
