name: Main workflow

on:
  push:
    branches:
    - notebook_first_trial
  pull_request:
    branches:
    - notebook_first_trial

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'notebook_first_trial'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
    - name: Install jupyter and pytest
      run: |
        pip install jupyter pytest

    - name: convert ipynb to py
      run: |
        jupyter nbconvert --to python notebooks/*.ipynb --output-dir=auto_generated_scripts

    - name: Run tests on notebooks and scripts
      run: |
        pytest

    - name: Build the book
      run: |
        pip install -r requirements.txt
        jupyter-book build ./

    - name: Push py files to github
      uses: patel-zeel/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'notebook_first_trial' #optional defaults to master
        files: 'auto_generated_scripts/*.py'
      if: github.event_name == 'push'  # Don't run on pull requests

    - name: Push jupyter-book to gh-pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
      if: github.event_name == 'push'  # Don't run on pull requests
