name: Main workflow

on:
  push:
    branches:
    - notebook_first_trial
  pull_request:
    branches:
    - notebook_first_trial

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'notebook_first_trial'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
    - name: Install jupyter and pytest
      run: |
        pip install jupyter pytest

    - name: convert ipynb to py
      run: |
        jupyter nbconvert --to python notebooks/*.ipynb --output-dir=auto_generated_scripts

    # - name: Run tests on notebooks and scripts
    #   run: |
    #     pytest

    # - name: Build the book
    #   run: |
    #     pip install -r requirements.txt
    #     jupyter-book build ./
    - name: Check it
      run: |
        echo "hello" > hello.txt

    # Commit py files (does not run on pull requests)
    - name: Commit py files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add auto_generated_scripts/*.py
        git commit -m "auto generated py files"
      if: github.event_name == 'push'  # Don't run on pull requests
    # Push py files to the repository and commit (does not run on pull requests)
    - name: Push py files to github
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      if: github.event_name == 'push'  # Don't run on pull requests

    - name: Push jupyter-book to gh-pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
      if: github.event_name == 'push'  # Don't run on pull requests
