name: Run tests

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'notebook_first_trial'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
    - name: install jupyter and pytest
      run: |
        pip install jupyter pytest
    - name: Run tests
      run: |
        pytest